- name: Debug Playbook 
  hosts: all
  gather_facts: False
  any_errors_fatal: True

  tasks:

  - name: get vyos facts
    vyos.vyos.vyos_facts:

  - name: output all fatcs
    debug:
      var: hostvars[inventory_hostname]


