- name: Automatic VyOS Lab test 
  hosts: all
  gather_facts: False
  any_errors_fatal: True

  roles:
    - role: eve-ng-create-node
      when: inventory_hostname in groups['eve']

    - role: eve-ng-lab-test


