- name: prepare node and Lab
  hosts: all
  gather_facts: False
  any_errors_fatal: True

  roles:
    - role: eve-ng-create-node
      when: inventory_hostname in groups['eve']

    - role: eve-ng-lab-test



  vars:
    output_dir: "vyos-documentation/docs/configexamples/autotest/{{ lab }}"
    output_include_dir: "_include"

    node_template_iso: "https://s3.amazonaws.com/s3-us.vyos.io/snapshot/vyos-1.3.0-rc6/vyos-1.3.0-rc6-amd64.iso"
    node_template_version: 1.4-rolling-202104132216

    upgrade_iso: "https://s3.amazonaws.com/s3-us.vyos.io/rolling/current/vyos-1.4-rolling-202111090317-amd64.iso"
    upgrade_iso_version: 1.4-rolling-202111090317