---

# reboot drive me crazy.
# Workaround: reboot in 1 minute, the task don't fail, b/c the connection will not be lost
- name: "{{ lab }}: Reboot vyos"
  vyos.vyos.vyos_command:
    commands: reboot in 1

# wait to boot, 60 + x seconds
- name: "{{ lab }}: wait while shutdown"
  pause:
    seconds: 70

# wait until vyos ist booted
- name: "{{ lab }}: Wait for vyos nodes"
  wait_for_connection: