---

- name: wait, b/c the ping often failed without a short break
  pause:
    seconds: 30

- name: do ping test
  vyos.vyos.vyos_ping:
    dest: "{{ item }}"
  with_items: "{{ lab_vars.tests.ping }}"
  when: lab_vars.tests.ping is defined

- name: execute test commands
  vyos.vyos.vyos_command:
    commands: "{{ item.command }}"
    wait_for: "{{ item.wait_for }}"
  with_items: "{{ lab_vars.tests.commands }}"
  when: lab_vars.tests.commands is defined


- name: register stdout commands
  vyos.vyos.vyos_command:
    commands: "{{ item.command }}"
  with_items: "{{ lab_vars.tests.stdout }}"
  when: lab_vars.tests.stdout is defined
  register: stdout_results

- name: Set variables
  set_fact:
    stdout: "{{ stdout_results.results }}"
  when: stdout_results.skipped == False


#- debug:
#    msg: "{{ stdout_result }}"