---

# genertate outputfiles

- name: make sure output dir exist
  delegate_to: localhost
  ansible.builtin.file:
    path: "{{ output_dir }}"
    state: directory

- name: make sure output include dir exist
  delegate_to: localhost
  ansible.builtin.file:
    path: "{{ output_dir }}/{{ output_include_dir }}"
    state: directory

- name: Get timestamp from the system
  shell: "date +%Y-%m-%d"
  register: tstamp

- name: Set variables
  set_fact:
    current_date: "{{ tstamp.stdout }}"

- name: generate lab rst file
  delegate_to: localhost
  template: 
    src: labs/{{ lab }}/{{ lab }}.rst.j2
    dest: "{{ output_dir }}/{{ lab }}.rst"

- name: find all *.conf files in Lab
  delegate_to: localhost
  find:
    paths: labs/{{ lab }}
    patterns: '*.conf'
  register: conf_files

- name: copy all *.conf files
  delegate_to: localhost
  template: 
    src: "{{ item.path }}"
    dest: "{{ output_dir }}/{{ output_include_dir }}/{{ item.path.split('/')[-1] }}"
  with_items: "{{ conf_files.files }}"


- name: find all *.png files in Lab
  delegate_to: localhost
  find:
    paths: labs/{{ lab }}
    patterns: '*.png'
  register: png_files

- name: copy all *.png files
  delegate_to: localhost
  copy: 
    src: "{{ item.path }}"
    dest: "{{ output_dir }}/{{ output_include_dir }}/{{ item.path.split('/')[-1] }}"
  with_items: "{{ png_files.files }}"

- name: copy ansible log files
  delegate_to: localhost
  copy: 
    src: "logs/{{ lab }}"
    dest: "{{ output_dir }}/{{ lab }}.log"