---

- import_tasks: 01_env_vars.yml

- import_tasks: 02_startupconfig.yml

- name: "{{ lab }}: fail if node_template_version is empty"
  fail: msg="The variable 'node_template_version' is empty"
  when: node_template_version == ""

- import_tasks: 10_pretest_lab.yml
  when: inventory_hostname in groups['eve']

- import_tasks: 20_prepare_lab.yml


- name: include {{ lab }} lab_config.yml
  import_tasks: "labs/{{ branch }}/{{ lab }}/lab_config.yml"
  #when: inventory_hostname in groups['vyos']

- import_tasks: 30_test_lab.yml

# reboot and test again

- import_tasks: 22_reboot_vyos.yml
  when: inventory_hostname in groups['vyos']

- import_tasks: 30_test_lab.yml

- name: include upgrade and 2nd test
  block:
    - import_tasks: 21a_handle_iso.yml
      when: inventory_hostname in groups['eve']

    - import_tasks: 21_upgrade_vyos.yml
      when: inventory_hostname in groups['vyos']

    - import_tasks: 30_test_lab.yml
  when: upgrade


- import_tasks: 40_generate_output.yml
  when: inventory_hostname in groups['eve']

- import_tasks: 50_destroy_lab.yml
  when: inventory_hostname in groups['eve']

