---

- fail: msg="The variable 'node_template_version' is empty"
  when: node_template_version == ""

- include: 01_pretest_lab.yml
  when: inventory_hostname in groups['eve']

- include: 02_prepare_lab.yml


- name: include {{ lab }} lab_config.yml
  include: "labs/{{ lab }}/lab_config.yml"
  when: inventory_hostname in groups['vyos']

- include: 03_test_lab.yml

- include: 04_generate_output.yml
  when: inventory_hostname in groups['eve']

- include: 05_destroy_lab.yml
  when: inventory_hostname in groups['eve']

