---

- fail: msg="The variable 'node_template_version' is empty"
  when: node_template_version == ""

- include: 10_pretest_lab.yml
  when: inventory_hostname in groups['eve']

- include: 20_prepare_lab.yml


- name: include {{ lab }} lab_config.yml
  include: "labs/{{ lab }}/lab_config.yml"
  when: inventory_hostname in groups['vyos']


- include: 30_test_lab.yml

# reboot and test again

- include: 22_reboot_vyos.yml
  when: inventory_hostname in groups['vyos']

- include: 30_test_lab.yml

- name: include upgrade and 2nd test
  block:
    - include: 21_upgrade_vyos.yml
      when: inventory_hostname in groups['vyos']

    - include: 30_test_lab.yml
  when: upgrade


- include: 40_generate_output.yml
  when: inventory_hostname in groups['eve']

- include: 50_destroy_lab.yml
  when: inventory_hostname in groups['eve']

